version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 1433
      DB_NAME: TestDB
      DB_USER: sa
      DB_PASSWORD: Your_password123
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y