# config.etl.yaml
version: "1.0"
sql:
  accountSQL: 'select * from account'
  holdingSQL: 'select * from holding'
outputFile:
  accountFile: 'test/test-feed/test-out/account-data.csv'
  holdingFile: 'test/test-feed/test-out/holding-data.csv'
