# Use the official image as a parent image
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set the working directory
WORKDIR /Users/joeylam/repo/njs/njstool

# Copy the setup script to the Docker image
COPY ./database  .

# Set environment variables
ENV SA_PASSWORD=YourStrong!Password123
ENV ACCEPT_EULA=Y

# Expose port 1433
EXPOSE 1433

# Run the command on container startup
CMD /opt/mssql/bin/sqlservr