name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm ci

    - name: Run automated tests
      run: npm run test

    - name: merge test reports
      run: npm run test:reports      

    - name: Upload Cucumber HTML report
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-report
        path: coverage-cucumber/cucumber.html

    - name: Upload line of coverage HTML report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/index.html
        
    - name: Publish Test Results
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: 'reports/*.xml'
